package yio.io.sifaapp.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.raizlabs.android.dbflow.annotation.Column;
import com.raizlabs.android.dbflow.annotation.PrimaryKey;
import com.raizlabs.android.dbflow.annotation.Table;
import com.raizlabs.android.dbflow.structure.BaseModel;

import yio.io.sifaapp.utils.SifacDataBase;

/**
 * Entity mapped to table "CATEGORIA".
 */
@Table(databaseName = SifacDataBase.NAME)
public class Categoria extends BaseModel {
    @Column
    @PrimaryKey
    private Integer CategoriaID;
    @Column
    private String Descripcion;
    @Column
    private String Nombre;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Categoria() {
    }

    public Categoria(Integer CategoriaID, String Descripcion, String Nombre) {
        this.CategoriaID = CategoriaID;
        this.Descripcion = Descripcion;
        this.Nombre = Nombre;
    }

    public Integer getCategoriaID() {
        return CategoriaID;
    }

    public void setCategoriaID(Integer CategoriaID) {
        this.CategoriaID = CategoriaID;
    }

    public String getDescripcion() {
        return Descripcion;
    }

    public void setDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

    public String getNombre() {
        return Nombre;
    }

    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    public String toString() {
        return Nombre;
    }
}
