package yio.io.sifaapp.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.raizlabs.android.dbflow.annotation.Column;
import com.raizlabs.android.dbflow.annotation.PrimaryKey;
import com.raizlabs.android.dbflow.annotation.Table;
import com.raizlabs.android.dbflow.structure.BaseModel;

import yio.io.sifaapp.utils.SifacDataBase;


/**
 * Entity mapped to table "CIUDAD".
 */
@Table(databaseName = SifacDataBase.NAME)
public class Ciudad  extends BaseModel {
    @Column
    private String Nombre;
    @PrimaryKey
    @Column
    private Integer StbCiudadID;
    @Column
    private Integer objPaisID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Ciudad() {
    }

    public Ciudad(String Nombre, Integer StbCiudadID, Integer objPaisID) {
        this.Nombre = Nombre;
        this.StbCiudadID = StbCiudadID;
        this.objPaisID = objPaisID;
    }

    public String getNombre() {
        return Nombre;
    }

    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

    public Integer getStbCiudadID() {
        return StbCiudadID;
    }

    public void setStbCiudadID(Integer StbCiudadID) {
        this.StbCiudadID = StbCiudadID;
    }

    public Integer getObjPaisID() {
        return objPaisID;
    }

    public void setObjPaisID(Integer objPaisID) {
        this.objPaisID = objPaisID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END
    public String toString() {
        return Nombre;
    }
}
