package yio.io.sifaapp.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.raizlabs.android.dbflow.annotation.Column;
import com.raizlabs.android.dbflow.annotation.PrimaryKey;
import com.raizlabs.android.dbflow.annotation.Table;
import com.raizlabs.android.dbflow.structure.BaseModel;

import yio.io.sifaapp.utils.SifacDataBase;

@Table(databaseName = SifacDataBase.NAME  )
public class Configuration extends BaseModel {

    @Column
    @PrimaryKey
    private Integer objEmpleadoID;
    @Column
    private Boolean HasAccess;
    @Column
    private String SsgCuentaID;
    @Column
    private String Login;
    @Column
    private String Clave;

    public Boolean getSession() {
        return Session;
    }

    public void setSession(Boolean session) {
        Session = session;
    }

    @Column
    private Boolean Session;

    public Boolean getSystem() {
        return System;
    }

    public void setSystem(Boolean system) {
        System = system;
    }

    @Column
    private Boolean System;

    public Configuration() {}

    public Boolean getHasAccess() {
        return HasAccess;
    }

    public void setHasAccess(Boolean hasAccess) {
        HasAccess = hasAccess;
    }

    public Integer getObjEmpleadoID() {
        return objEmpleadoID;
    }

    public void setObjEmpleadoID(Integer objEmpleadoID) {
        this.objEmpleadoID = objEmpleadoID;
    }

    public String getClave() {
        return Clave;
    }

    public void setClave(String clave) {
        Clave = clave;
    }

    public String getLogin() {
        return Login;
    }

    public void setLogin(String login) {
        Login = login;
    }

    public String getSsgCuentaID() {
        return SsgCuentaID;
    }

    public void setSsgCuentaID(String ssgCuentaID) {
        SsgCuentaID = ssgCuentaID;
    }
}
