package yio.io.sifaapp.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.raizlabs.android.dbflow.annotation.Column;
import com.raizlabs.android.dbflow.annotation.PrimaryKey;
import com.raizlabs.android.dbflow.annotation.Table;
import com.raizlabs.android.dbflow.structure.BaseModel;

import java.io.Serializable;
import java.util.Date;

import yio.io.sifaapp.utils.SifacDataBase;

/**
 * Entity mapped to table "CUSTOMER".
 */
@Table(databaseName = SifacDataBase.NAME)
public class Customer extends BaseModel implements Serializable {

    @Column
    @PrimaryKey
    private int ClienteID;
    @Column
    private String Apellido2;
    @Column
    private String Apellido1;

    @Column
    private String Cedula;
    @Column
    private String Ciudad;
    @Column
    private String Direccion;
    @Column
    private Integer StbRutaID;
    /*
    @Column
    private Date FechaNacimiento;

    */
    @Column
    private String Genero;
    @Column
    private String Nombre1;
    @Column
    private String Nombre2;
    @Column
    private Integer OrdenCobro;
    @Column
    private String Pais;
    @Column
    private String RutaAsignada;
    @Column
    private String Telefonos;
    @Column
    private Integer objCiudadID;
    @Column
    private Integer objGeneroID;
    @Column
    private Integer objPaisID;
    @Column
    private Integer ojbCobradorID;
    @Column
    private Boolean offline;
    @Column
    private String Referencia;

    public Boolean getOfflineReferencia() {
        return offlineReferencia;
    }

    public void setOfflineReferencia(Boolean offlineReferencia) {
        this.offlineReferencia = offlineReferencia;
    }

    public Boolean getOfflineOrdenCobro() {
        return offlineOrdenCobro;
    }

    public void setOfflineOrdenCobro(Boolean offlineOrdenCobro) {
        this.offlineOrdenCobro = offlineOrdenCobro;
    }

    @Column
    private Boolean offlineReferencia;
    @Column
    private Boolean offlineOrdenCobro;


    public String getReferencia() {
        return Referencia;
    }

    public void setReferencia(String referencia) {
        Referencia = referencia;
    }

    public Integer getStbRutaID() {
        return StbRutaID;
    }

    public void setStbRutaID(Integer stbRutaID) {
        StbRutaID = stbRutaID;
    }

    public void setObjCiudadID(int objCiudadID) {
        this.objCiudadID = objCiudadID;
    }

    public Boolean getOffline() {
        return offline;
    }

    public void setOffline(Boolean offline) {
        this.offline = offline;
    }
// KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Customer() {
    }


    public String getApellido2() {
        return Apellido2;
    }

    public void setApellido2(String Apellido2) {
        this.Apellido2 = Apellido2;
    }

    public String getApellido1() {
        return Apellido1;
    }

    public void setApellido1(String Apellido1) {
        this.Apellido1 = Apellido1;
    }

    public String getCedula() {
        return Cedula;
    }

    public void setCedula(String Cedula) {
        this.Cedula = Cedula;
    }

    public String getCiudad() {
        return Ciudad;
    }

    public void setCiudad(String Ciudad) {
        this.Ciudad = Ciudad;
    }

    public int getClienteID() {
        return ClienteID;
    }

    public void setClienteID(Integer ClienteID) {
        this.ClienteID = ClienteID;
    }

    public String getDireccion() {
        return Direccion;
    }

    public void setDireccion(String Direccion) {
        this.Direccion = Direccion;
    }
    /*
    public Date getFechaNacimiento() {
        return FechaNacimiento;
    }

    public void setFechaNacimiento(Date FechaNacimiento) {
        this.FechaNacimiento = FechaNacimiento;
    }
*/
    public String getGenero() {
        return Genero;
    }

    public void setGenero(String Genero) {
        this.Genero = Genero;
    }

    public String getNombre1() {
        return Nombre1;
    }

    public void setNombre1(String Nombre1) {
        this.Nombre1 = Nombre1;
    }

    public String getNombre2() {
        return Nombre2;
    }

    public void setNombre2(String Nombre2) {
        this.Nombre2 = Nombre2;
    }

    public Integer getOrdenCobro() {
        return OrdenCobro;
    }

    public void setOrdenCobro(Integer OrdenCobro) {
        this.OrdenCobro = OrdenCobro;
    }

    public String getPais() {
        return Pais;
    }

    public void setPais(String Pais) {
        this.Pais = Pais;
    }

    public String getRutaAsignada() {
        return RutaAsignada;
    }

    public void setRutaAsignada(String RutaAsignada) {
        this.RutaAsignada = RutaAsignada;
    }

    public String getTelefonos() {
        return Telefonos;
    }

    public void setTelefonos(String Telefonos) {
        this.Telefonos = Telefonos;
    }

    public Integer getObjCiudadID() {
        return objCiudadID;
    }

    public void setObjCiudadID(Integer objCiudadID) {
        this.objCiudadID = objCiudadID;
    }

    public Integer getObjGeneroID() {
        return objGeneroID;
    }

    public void setObjGeneroID(Integer objGeneroID) {
        this.objGeneroID = objGeneroID;
    }

    public Integer getObjPaisID() {
        return objPaisID;
    }

    public void setObjPaisID(Integer objPaisID) {
        this.objPaisID = objPaisID;
    }

    public Integer getOjbCobradorID() {
        return ojbCobradorID;
    }

    public void setOjbCobradorID(Integer ojbCobradorID) {
        this.ojbCobradorID = ojbCobradorID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    public Object isMatch(CharSequence constraint) {
        if (getNombreCliente().toLowerCase().contains(constraint.toString()))
            return true;
        return false;
    }

    public String getNombreCliente(){
        return getNombre1() + " " + getNombre2() +" " + getApellido1() +" " + getApellido2() ;
    }
}
