package yio.io.sifaapp.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.raizlabs.android.dbflow.annotation.Column;
import com.raizlabs.android.dbflow.annotation.PrimaryKey;
import com.raizlabs.android.dbflow.annotation.Table;
import com.raizlabs.android.dbflow.structure.BaseModel;

import yio.io.sifaapp.utils.SifacDataBase;

/**
 * Entity mapped to table "DESCUENTO".
 */
@Table(databaseName = SifacDataBase.NAME)
public class Descuento  extends BaseModel {
    @Column
    private Float DescuentoMaximo;
    @Column
    private Float DescuentoMinimo;
    @Column
    private Float PlazoPago;
    @PrimaryKey
    @Column
    private int SccDescuentoID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Descuento() {
    }

    public Descuento(Float DescuentoMaximo, Float DescuentoMinimo, Float PlazoPago, int SccDescuentoID) {
        this.DescuentoMaximo = DescuentoMaximo;
        this.DescuentoMinimo = DescuentoMinimo;
        this.PlazoPago = PlazoPago;
        this.SccDescuentoID = SccDescuentoID;
    }

    public Float getDescuentoMaximo() {
        return DescuentoMaximo;
    }

    public void setDescuentoMaximo(Float DescuentoMaximo) {
        this.DescuentoMaximo = DescuentoMaximo;
    }

    public Float getDescuentoMinimo() {
        return DescuentoMinimo;
    }

    public void setDescuentoMinimo(Float DescuentoMinimo) {
        this.DescuentoMinimo = DescuentoMinimo;
    }

    public Float getPlazoPago() {
        return PlazoPago;
    }

    public void setPlazoPago(Float PlazoPago) {
        this.PlazoPago = PlazoPago;
    }

    public int getSccDescuentoID() {
        return SccDescuentoID;
    }

    public void setSccDescuentoID(int SccDescuentoID) {
        this.SccDescuentoID = SccDescuentoID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
